### ISSUE TITLE
Installation is failing.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [lnxusr1/karen#9]
Hi. I was trying the installation method in the readme. But the pip installation is failing. I tried Python 3.9(Local|Conda) and Python 3.7(Colab). Wondering what will be the cause of the issue?

I am attaching the [link](https://colab.research.google.com/drive/1O6BS2V1IA1yW-lARpOw1E1YDxxzTKfw8?usp=sharing) to the notebook to reproduce the issue.

**Comment by lnxusr1** [comment]
That's my bad.  It seems from your log that it has a dependency on "karen-listener" and should be on "karen-plugin-listener"

The package name was changed in a recent version.  I'll get it fixed/committed as soon as possible.  In the meantime you should be able to install just ignoring dependencies or grab the latest source.

**Comment by lnxusr1** [comment]
I've been going back through your log try see if I can figure out exactly what your issue is.  Can you share the following?

* Python Version (python3 --version)
* List of Python packages & their versions installed (pip3 list)
* List of OS packages & their versions installed (dpkg -l)
 
And also confirm you are using the Python 3 and not Python 2.

The error you're getting appears to be this:
self.fd_to_silence = stream.fileno() 

That is used to silence a bunch of errors that aren't really errors.  I can pull that logic since it doesn't hurt to show them other than likely leading folks off in the wrong direction on problems.  The "fileno()" function is built into Python so I'm thinking this is version specific.

**Comment by lnxusr1** [comment]
I've fully installed Karen 0.7.0 onto a Ubuntu 20.04 LTS Bionic Beaver virtual machine and it ran successfully suggesting it must be something with the versioning so let me know when you have those details and I'll dig further.

**Comment by Sreerag-ibtl** [comment]
@lnxusr1 My local machine is Ubuntu 16.04. On which I was not able to install the packages since the package _festvox-us-slt-hts_ is not available. So, I tried Colab. The python version is  3.7.12. The Python and Debian package lists are updated in the notebook shared earlier.

**Comment by lnxusr1** [comment]
The io.unsupportedOperation in fileno indicates unsupported features in the platform you are using.  You can run on Ubuntu 16 just install festival without the extra voice.  It may sound more like a robot as the STS voices produce better human-like output but those are really outside the scope of Karen's code anyway.

The specific fileno issue is with the class "SilentStream" which is used to prevent undesired STDOUT from deepspeech where they print the version number whether you want it or not with no way to suppress.  I raised an issue on their project but was basically told they aren't going to change it because too many people sent support tickets and don't think to include the version number so this way it is always there.  It's an idea, but frustrating for sure.

All this was because I was using a CLI only based visualizer so any undesired output to the console would mess up the display.  I've since switched to PyQt5 which is forms based (and optional) and so the SilentStream class is not really required any longer.  I'll look into adding an option to disable it for version 0.8.1, but for now your platform isn't supported with the listener device.
